import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from docs/adr/. New ADRs appear without touching this file.
const sidebars: SidebarsConfig = {
  adr: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
